name: setup-mysql-docker

on:
  push:
    branches:
      - main

jobs:
  setup-mysql-environment:
    name: setup-mysql-environment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Setup Zookeeper
        run: docker run -itd -e MYSQL_ROOT_PASSWORD=root -p13306:3306 mysql:8.0.28

      - name: Wait Docker Container
        run: sleep 15
        
      - name: Check Docker Status
        run: sudo docker ps
        
      - name: Check Service Status
        run: sudo lsof -i:13306
