name: setup-proxy-docker

on:
  push:
    branches:
      - main

jobs:
  setup-mysql-environment:
    name: setup-proxy-environment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: show path
        run pwd
#      - name: Setup Zookeeper
#        run: |
#          sudo docker run -itd -e MYSQL_ROOT_PASSWORD=${{ secrets.RootPassword }} -p13306:3306 mysql:8.0.28
#          sudo docker run -itd -p 2181:2181 zookeeper:3.7.0
#
#      - name: Waiting for Container
#        run: sleep 15
#        
#      ## the following code is for checking the MySQL instance
#      - name: Create DB structure
#        run: |
#          sudo /lib/systemd/systemd-sysv-install enable mysql
#          sudo systemctl enable mysql.service
#          sudo systemctl start mysql.service
#          sudo systemctl status mysql.service
#      
#      - name: Setup Proxy
#        run: docker run ghcr.io/apache/shardingsphere-proxy:latest