name: setup-mysql-docker

on:
  push:
    branches:
      - main

jobs:
  setup-mysql-environment:
    name: setup-mysql-environment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Setup Zookeeper
        run: docker run -itd -e MYSQL_ROOT_PASSWORD=${{ secrets.RootPassword }} -p13306:3306 mysql:8.0.28

      - name: Wait Docker Container
        run: sleep 15
        
      - name: Check Docker Status
        run: sudo docker ps
        
      - name: Check Service Status
        run: sudo lsof -i:13306

      ## the following code is for checking the MySQL instance
      - name: Create DB structure
        run: |
          sudo /lib/systemd/systemd-sysv-install enable mysql
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          sudo systemctl status mysql.service

      - name: Waiting MySQL
        run: sleep 15

      - name: Get The MySQL Result
        run: mysql -h127.0.0.1 -P13306 -p${{ secrets.RootPassword }} -uroot -e "SELECT t.* FROM information_schema.USER_PRIVILEGES t limit 10"
